version: 2.1
welcome: circleci/welcome-orb@0.4.1
jobs:
  build_and_save:
    steps:
    - checkout
    - run: npm install --ignore-engines
    - run: npm run jest
    - store_artifacts:
      path: coverage

workflows:
  version: 2
  main:
    jobs:
      - build_and_save